### PR TITLE
Used right enum namespace

### PR DESCRIPTION
**Pull request by ahcorde**
Signed-off-by: ahcorde <ahcorde@gmail.com>

# 🦟 Bug fix

## Summary

This PR https://github.com/gazebosim/sdformat/pull/1029 in SDFormat changes the enum namespace.  This PR fixed the enums.

We need to wait for a nightly release

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [x] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [x] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [x] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by azeey** [comment]
We'll need to trigger the nightly build of SDFormat.

**Comment by scpeters** [comment]
> We'll need to trigger the nightly build of SDFormat.
> 
> [Build Status](https://build.osrfoundation.org/job/sdformat13-debbuilder/299/)

that build succeeded, but it didn't have an incremented `RELEASE_VERSION` so it failed to upload:

* [Build Status](https://build.osrfoundation.org/view/ign-garden/job/repository_uploader_packages/26077/) https://build.osrfoundation.org/view/ign-garden/job/repository_uploader_packages/26077/

I've started new nightly builds with `RELEASE_VERSION` == 2

* [Build Status](https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/300/) https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/300/
* [Build Status](https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/301/) https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/301/

**Comment by azeey** [comment]
> > We'll need to trigger the nightly build of SDFormat.
> > [Build Status](https://build.osrfoundation.org/job/sdformat13-debbuilder/299/)
> 
> that build succeeded, but it didn't have an incremented `RELEASE_VERSION` so it failed to upload:
> 
> * [Build Status](https://build.osrfoundation.org/view/ign-garden/job/repository_uploader_packages/26077/) https://build.osrfoundation.org/view/ign-garden/job/repository_uploader_packages/26077/
> 
> I've started new nightly builds with `RELEASE_VERSION` == 2
> 
> * [Build Status](https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/300/) https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/300/
> * [Build Status](https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/301/) https://build.osrfoundation.org/view/ign-garden/job/sdformat13-debbuilder/301/

hmm, I didn't think it needed it because it would be building from a new commit.

**Comment by azeey** [comment]
Conflicts

**Comment by scpeters** [comment]
> hmm, I didn't think it needed it because it would be building from a new commit.

while the commit hash is embedded in the file name, I believe it isn't used for sorting since it's not guaranteed to be monotonically increasing. I believe the release version needs to be incremented

**Review by scpeters — APPROVED** [review]

**Comment by azeey** [comment]
I think codecov is complaining about removed lines. Doesn't seem like a real decrease in coverage. Will go ahead and merge.

**Pull request merged**
