### PR TITLE
Add support for `compiler.eulerseq="xyz"`

### PR DESCRIPTION
**Pull request by azeey**
# 🎉 New feature

## Summary
By default MJCF uses Euler angles with the `xyz` convention (rotation in x, followed by new/local y, followed by new/local z), but SDFormat uses `XYZ` (rotation in x, followed by global y, followed by global z). MJCF also supports other euler conventions via `compiler.eulerseq`, but supporting all the other conventions is not trivial. I'll create an issue to track that.

## TODO:
- [x] Add test

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

### CODE REVIEW

**Comment by scpeters** [comment]
is there a particular example world that would illustrate this difference?

**Comment by ahcorde** [comment]
> is there a particular example world that would illustrate this difference?

manipulator.xml ?

**Comment by azeey** [comment]
Yes, manipulator.xml is a good one.

Here's one for experimenting with different parameters
```xml
<mujoco model="test_model">
  <!--<compiler eulerseq="XYZ"/>-->


  <default>
    <geom type="capsule" size="0.02"/>
  </default>
  <asset>
    <texture name="grid" type="2d" builtin="checker" width="512" height="512" rgb1=".1 .2 .3" rgb2=".2 .3 .4"/>
    <material name="grid" texture="grid" texrepeat="1 1" texuniform="true" reflectance=".2"/>
  </asset>
  <visual>
    <headlight diffuse="1 1 1"/>
  </visual>
  <worldbody>
    <geom name="floor" size="0 0 0.005" type="plane" material="grid"/>

    <body name="fixed_axes" pos="0 0 0">
      <geom name="X" fromto="0 0 0 10 0 0" rgba="1 0 0 1"/>
      <geom name="Y" fromto="0 0 0 0.0 10 0" rgba="0 1 0 1"/>
      <geom name="Z" fromto="0 0 0 0.0 0.0 10" rgba="0 0 1 1"/>
    </body>

    <body name="axes" pos="1 1 1" euler="0 90 30" >
      <geom name="x" fromto="0 0 0 0.3 0 0" rgba="1 0 0 1"/>
      <geom name="y" fromto="0 0 0 0.0 0.3 0" rgba="0 1 0 1"/>
      <geom name="z" fromto="0 0 0 0.0 0.0 0.3" rgba="0 0 1 1"/>
    </body>
  </worldbody>
</mujoco>
```

**Review by ahcorde — APPROVED** [review]
@azeey we should merge this one too

**Comment by azeey** [comment]
> @azeey we should merge this one too

Added a test in https://github.com/gazebosim/gz-mujoco/pull/90/commits/dfd7192af552ed691af87760deec4aa77fc61f25. Can you PTAL?

**Review by ahcorde — APPROVED** [review]

**Pull request merged**
