### PR TITLE
Use a single namespace and subpackages

### PR DESCRIPTION
**Pull request by j-rivero**
The PR moves the current packages under a common [native namespace ](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/#native-namespace-packages) named `sdformat_mjcf`.

With the change, we might want to reconsider the way of invoking our imports, probably need to work using the schema `from sdformat_mjcf.sdformat_to_mjcf import foo` since the installation using PYPI is probably installing the code using that directory layout. By now, things keep working since we are injecting `PYTHONPATH` in CI to point to the subpackages.

I've manually uploaded a test to test.pypi.org using the initial state of this PR https://test.pypi.org/project/sdformat-mjcf/. I'll send a second PR with the automated code for this.

### CODE REVIEW

**Review by azeey — COMMENTED** [review]
Right now both `sdformat_to_mjcf` and `sdformat_mjcf_utils` have a setup.py file. Do we need that if we're putting them all in one PyPI package?

**Comment by j-rivero** [comment]
> Right now both `sdformat_to_mjcf` and `sdformat_mjcf_utils` have a setup.py file. Do we need that if we're putting them all in one PyPI package?

Oh, that is right, I think we don't need to ship more `setup.py` than the one in root. I went a bit crazy and do the following in [12231f4](https://github.com/gazebosim/gz-mujoco/pull/39/commits/12231f4b1ca2e1e672c289ab26806f659d086cb4):

 * Get rid of the duplicate directories `sdformat_to_mjcf/sdformat_to_mjcf` move all files to the upper dir
 * Remove all __init__.py but leave the ones in real packages, otherwise they are recognized as packages and installed
 * Remove setup.py, LICENSE, README, setup.cfg, etc. from subpackages, leave just one in the root dir
 * Change setup.py to install the `sdformat2mjcf` script in entry
 * Change cli.py to get the new paths (**TODO**: we probably need to extend the new syntax in all files).

With this, I'm able to do the following:
```
> virtualenv foo && source foo/bin/activate && pip install .
> sdformat2mjcf
```
And `python3 setup.py sdist bdist bdist_wheel` output also looks good to me.

What I think it is missing:
 * Change all the imports to the new layout `sdformat_mfjc.$package`
 * Probably leave a single tox.ini file covering both packages

**Comment by azeey** [comment]
Okay, but now this puts files in the root directory `gz-mujoco`. We don't want `gz-mujoco` to be a python package. If we're putting them all in one package, we should just have `sdformat_mjcf` as the only directory in the root of the repo and no other files for now.

**Comment by azeey** [comment]
Okay, but now this puts files in the root directory `gz-mujoco`. We don't want `gz-mujoco` to be a python package. If we're putting them all in one package, we should just have `sdformat_mjcf` as the only directory in the root of the repo and no other files for now.

**Pull request closed without merging**
